### ISSUE TITLE
All Messages are send as ''Normal''

### ISSUE THREAD

**Issue by CliffBroeren** [PandaNL/nl.tonversteeg.pushover#21]
Since The update Beta is Stable off Pushover

All the Messages are send as ''Normal'' 
Even when I try to send a message to a specific device it's send to All the devices.

the problem is on homey FW 1.5.13 and also on FW 2.0

It is really ignoring because I get a lot of push messages a day that before the update are send as ''Lowest''

**Comment by SkorpionNL** [comment]
I also have this problem. Homey FW 2.0.2

**Comment by CliffBroeren** [comment]
This only works until you open the app or for a couple of hours

**Comment by CliffBroeren** [comment]
Are they any updates on this issue ??? @PandaNL ?

**Comment by SkorpionNL** [comment]
Yep, I noticed that also. Still having the problems.

**Comment by CliffBroeren** [comment]
Any Updates  from this Issue ???

**Comment by Veldkornet** [comment]
Is this not because the [Pushover API](https://pushover.net/api#priority) states that when sending priority 2 messages, the **retry** and **expire** parameters must be passed?

I didn’t see this configured anywhere.

**Comment by Veldkornet** [comment]
@PandaNL I've done some testing, and the parameters are all still being passed on correctly. 

It seems as though the problem is with your dependencey of [Pushover-notification-client]( https://github.com/ketra/Pushover-notification-client). I switched over to [node-pushover](https://github.com/qbit/node-pushover) and the priorities started working.

Although just blindly switching seems to break things like the image token etc.

But at least you know now where to look. I've logged an [issue](https://github.com/ketra/Pushover-notification-client/issues/1) for it there... who knows :)

**Comment by ketra** [comment]
I have localised the issue and will try publish a new version today or tomorrow where this is fixed

**Comment by SkorpionNL** [comment]
Great!

**Comment by ketra** [comment]
note: a new version of Pushover-notification-client

**Comment by Veldkornet** [comment]
Thanks @ketra .

FYI, I think I managed to fix it as well. I have it working with both High and Emergency priority

I've bundled everything into Pull request [24](https://github.com/PandaNL/nl.tonversteeg.pushover/pull/24)

**Comment by SkorpionNL** [comment]
Nice job @Veldkornet! Will try your PR later today if I find some time.

**Comment by ketra** [comment]
new version of Pushover-notification-client. is up on NPM. this also fixes sending to device #22

**Comment by PandaNL** [comment]
@Veldkornet Thank you for your hard work, I just pushed beta 0.0.12 for approval.
